filebeat.inputs:
    - type: log
      paths:
        - /var/log/messages
        - /var/log/cron
        - /var/log/secure
        - /var/log/maillog
        - /var/log/firewalld
        - /var/log/docker
        - /var/log/secure
        - /var/log/*.log
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog
    - type: log
      paths:
        - /var/log/audit/audit.log*
      fields:
            clientip: PUBLIC_IP_ADDR
            type: audit
    - type: log
      paths:
        - /var/log/elasticsearch/*.log
      fields:
            clientip: PUBLIC_IP_ADDR
            type: elasticsearch
    - type: log
      paths:
        - /var/log/logstash/logstash-plain.log
      fields:
            clientip: PUBLIC_IP_ADDR
            type: logstash

    # CUCM CDR
    - type: log
      paths:
        - /home/data/cdr_cmr/cucm/*/cdr*
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: cucm_cdr

    # CUCM CMR
    - type: log
      paths:
        - /home/data/cdr_cmr/cucm/*/cmr*
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: cucm_cmr

    # CUCM logs
    - type: log
      paths:
        - /home/data/servers/*/cucm/local*.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_cucm_local
    - type: log
      paths:
        - /home/data/servers/*/cucm/user.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_cucm_user
    - type: log
      paths:
        - /home/data/servers/*/cucm/cron.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_cucm_cron
    - type: log
      paths:
        - /home/data/servers/*/cucm/authpriv.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_cucm_authpriv
    - type: log
      paths:
        - /home/data/servers/*/cucm/daemon.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_cucm_daemon
    - type: log
      paths:
        - /home/data/servers/*/cucm/kern.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_cucm_kernel

    # VCS logs
    - type: log
      paths:
        - /home/data/servers/*/vcs/syslog.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_vcs
    - type: log
      paths:
        - /home/data/servers/*/vcs/local*.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_vcs_local
    - type: log
      paths:
        - /home/data/servers/*/vcs/security.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_vcs_security
    - type: log
      paths:
        - /home/data/servers/*/vcs/user.log
      fields_under_root: true
      fields:
            clientip: PUBLIC_IP_ADDR
            type: syslog_vcs_user

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

output.logstash:
  hosts: ["localhost:5044"]
  ssl.enabled: false

#setup.kibana:
#  host: "localhost:5601"
logging.level: debug

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ['http://localhost:9200']

