filebeat.inputs:
    - type: log
      paths:
        - /var/log/messages
        - /var/log/cron
        - /var/log/secure
        - /var/log/maillog
        - /var/log/firewalld
        - /var/log/docker
        - /var/log/secure
        - /var/log/*.log
      fields:
            clientip: localhost
            type: syslog
    - type: log
      paths:
        - /var/log/audit/audit.log
      fields:
            clientip: localhost
            type: audit
    - type: log
      paths:
        - /var/log/elasticsearch/*.log
      fields:
            clientip: localhost
            type: elasticsearch
    - type: log
      paths:
        - /var/log/logstash/logstash-plain.log
      fields:
            clientip: localhost
            type: logstash

    # CUCM 
    ## - CDR
    - type: log
      paths:
        - /home/data/cdr_cmr/cucm/*/cdr*
      fields:
            clientip: localhost
            type: cucm_cdr

    ## - CMR
    - type: log
      paths:
        - /home/data/cdr_cmr/cucm/*/cmr*
      fields:
            clientip: localhost
            type: cucm_cmr

    ## - logs
    - type: log
      paths:
        - /home/data/servers/*/*cucm*/
      fields_under_root: true
      fields:
            clientip: localhost
            type: syslog_cucm

    # VCS
    ## - log 
    - type: log
      paths:
        - /home/data/servers/*/*vcs*/
      fields_under_root: true
      fields:
            clientip: localhost
            type: syslog_vcs
    ## - CDR/CMR
    - type: log
      paths:
        - /home/data/cdr_cmr/vcs/
      fields_under_root: true
      fields:
            clientip: localhost
            type: vcs_cdr_cmr
    # CMS
    ## - log
    - type: log
      paths:
        - /home/data/servers/*/*cms*/
      fields_under_root: true
      fields:
            clientip: localhost
            type: syslog_cms
    ## - CDR/CMR
    - type: log
      paths:
        - /home/data/cdr_cmr/cms/
      fields_under_root: true
      fields:
            clientip: localhost
            type: cms_cdr_cmr

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

output.logstash:
  hosts: ["ADDRIP_LOGSTASH:5044"]
  ssl.enabled: false

setup.kibana:
  host: "ADDRIP_KIBANA:5601"

logging.level: info

xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ['http://ADDR_IP_MASTER_1:9200']
